### ISSUE TITLE
Transparency of `queryableFullScreenCover`?

### ISSUE THREAD

**Issue by AndrewSB** [SwiftedMind/Queryable#4]
Hey! I'm trying to present a fullScreenCover that just has a text field at the top of the screen, where the screen has a 50% black background

this was working for me fine when i used just `.fullscreenCover`, but after switching to `.queryableFullScreenCover`, there's a solid white layer between my cover and the presenting view

is there a hosting controller somewhere in here? can we make it's background transparent, if so?

if not, i can provide a small reproducible example for us to look at together

thanks for making this! really cool way of handling this state

**Comment by SwiftedMind** [comment]
Hey, I'm glad you like the framework :)

hm, I didn't know it was possible to have a transparent `fullScreenCover` in the first place 🤔. `queryableFullScreenCover ` is basically just a wrapper around `fullScreenCover`, there's no hosting controller or anything, it's pure SwiftUI.

An example would be great, yes. I'm happy to have a look at it :)

**Comment by AndrewSB** [comment]
ahh my mistake, making `fullScreenCover` involves a UIKit hack. you make the background of the presented view this `Hack_ClearBackgroundView`. using that hack, it works for this library too

here's an example:

```swift
struct Hack_ClearBackgroundView: UIViewRepresentable {
    func makeUIView(context: Context) -> UIView {
        let view = UIView()
        DispatchQueue.main.async {
            view.superview?.superview?.backgroundColor = .clear
        }
        return view
    }

    func updateUIView(_ uiView: UIView, context: Context) {}
}

struct ContentView: View {
    @State var overlaid = false

    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundColor(.accentColor)
            Button("Show", action: { overlaid.toggle() })
        }
        .tint(.white)
        .padding()
        .background(Color.red)
        .fullScreenCover(isPresented: $overlaid) {
            ZStack{
                Color.black.opacity(0.1).edgesIgnoringSafeArea(.all)
                VStack {
                    Text("hi")
                    Button("hide") {
                        overlaid.toggle()
                    }
                    Spacer()
                }
                .padding()
            }
            .background(Hack_ClearBackgroundView())
        }
    }
}
```

**Comment by SwiftedMind** [comment]
Ah okay, cool 😃
Glad it works 👍
